# Generated by Django 5.2.2 on 2025-07-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='show_mature_content',
            new_name='mature_content',
        ),
    ]
