# Generated by Django 5.2.4 on 2025-07-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_show_mature_content_to_mature_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'User Preference', 'verbose_name_plural': 'User Preferences'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userskill',
            options={'ordering': ['-proficiency_level', 'skill_name'], 'verbose_name': 'User Skill', 'verbose_name_plural': 'User Skills'},
        ),
        migrations.RemoveConstraint(
            model_name='userskill',
            name='unique_user_skill',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_profile_public',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state_province',
        ),
    ]
