# Generated by Django 5.2.3 on 2025-06-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='access_token_secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
