# Generated by Django 5.2.2 on 2025-06-22 22:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmediaaccount',
            unique_together={('user', 'platform')},
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='access_token_secret',
            field=models.CharField(blank=True, help_text='Access Token Secret for API requests.', max_length=255),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='api_key',
            field=models.CharField(blank=True, help_text='API Key from the social platform.', max_length=255),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='api_secret',
            field=models.CharField(blank=True, help_text='API Secret from the social platform.', max_length=255),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, help_text='The username or handle of the social media account.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='access_token',
            field=models.CharField(blank=True, help_text='Access Token for API requests.', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='account_id',
        ),
    ]
