name: Backend Security Scans

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  backend-security:
    runs-on: ubuntu-latest
    name: Run Backend Security Scans

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- Python Setup ---
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # --- Bandit Scan ---
      - name: Run Bandit and Save Report
        run: |
          pip install bandit
          bandit -r . -f html -o bandit-report.html || true
          if [ -f bandit-report.html ]; then echo "Bandit report generated"; else echo "No Bandit report found"; fi

      # --- Semgrep Scan ---
      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep and Save Report
        run: |
          semgrep scan --config=auto . --json > semgrep-report.json || true
          if [ -f semgrep-report.json ]; then echo "Semgrep report generated"; else echo "No Semgrep report found"; fi

      # --- OWASP Dependency-Check ---
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "ClientNest Backend"
          path: "."
          format: "HTML"
          out: "dc-reports"

      # --- Organize Reports Safely ---
      - name: Organize Reports
        run: |
          mkdir -p security-reports
          if [ -f bandit-report.html ]; then mv bandit-report.html security-reports/; fi
          if [ -f semgrep-report.json ]; then mv semgrep-report.json security-reports/; fi
          if [ -f dc-reports/dependency-check-report.html ]; then cp dc-reports/dependency-check-report.html security-reports/; fi

      # --- Upload All as "backend-security" Artifact ---
      - name: Upload Backend Security Report
        uses: actions/upload-artifact@v4
        with:
          name: backend-security
          path: security-reports
