# Generated by Django 5.2.2 on 2025-07-15 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_service', '0002_add_comment_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='content_service.post'),
        ),
    ]
